export const paths = {
    newPassword: "/new_password",
    setting: "/setting",
    clients: "/clients",
    company: "/company",
    about: "/about",
    admin:  "/admin",
    auth: "/auth",
    forget:"/forget",
    calls: "/calls",
    problems: "/problems",
    themes: "/themes",
    answers: "/answers",
    specialists: "/specialists",
    registration:  "/registration",
    FAQ: "/faq",
    code:"/code",
    oauth: "/oauth",
    main:  "/",
}