apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-call-center
spec:
  progressDeadlineSeconds: 240
  selector:
    matchLabels:
      app: call-center-pod
      tier: backend-call-center
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: call-center-pod
        tier: backend-call-center
        track: stable
    spec:
      volumes:
        - name: call-center-volume
          persistentVolumeClaim:
            claimName: call-center-persistent-volume-claim

      containers:
        - name: call-center-container
          image: grigorytitov/docker-call-center-backend-image:v1
          imagePullPolicy: Always #Для подгрузки обновлений с DockerHub
          #command: ["npm","test:db_tables"] #Для запуска тестов
          ports:
            - name: http
              containerPort: 6001
          env:
            - name: URL_SITE
              value: "https://localhost"
            - name: URL_BASE_INGRESS
              value: "https://localhost/api/v1/backend"
            #Internal services
            - name: DB_USER
              value: postgres
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "db_backend"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD

            - name: KAFKA_CLIENT_ID
              value: "backend-app"
            - name: KAFKA_BROCKERS_HOST
              value: kafka
            - name: KAFKA_BROCKERS_PORT
              value: "29092"
            - name: KAFKA_BROCKERS_REPLICATION_FACTOR
              value: "2"

            - name: REDIS_NAME
              value: ""
            - name: REDIS_PASSWORD
              value: ""
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "1"
          volumeMounts:
            - mountPath: /public
              name: call-center-volume