apiVersion: v1
kind: Service
metadata:
  name: backend-call-center
spec:
  selector:
    app: call-center-pod
    tier: backend-call-center
  ports:
  - protocol: TCP
    port: 6001
    targetPort: 6001
  type: LoadBalancer