apiVersion: v1
kind: Service
metadata:
  name: kafka
  labels:
    app: kafka-app
spec:
  clusterIP: None # For Headless Service
  ports:
    - name: kafka-port
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-app