apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  labels:
    app: kafka-app
spec:
  serviceName: kafka
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      app: kafka-app
  template:
    metadata:
      labels:
        app: kafka-app
      annotations:
        kafka.node.id: "1"
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: kafka
        image: bitnami/kafka:latest
        ports:
        - containerPort: 9092
          name: client
        - containerPort: 9093
          name: controller
        env:
        # Авто создание топиков
        - name:  KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_CFG_NUM_PARTITIONS
          value: "3"
        - name: KAFKA_CFG_DEFAULT_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        # Выключение ACL в KRaft-режиме
        - name: KAFKA_CFG_AUTHORIZER_CLASS_NAME
          value: ""

        # Настройки авторизации
        - name: KAFKA_CFG_SUPER_USERS
          value: "User:admin"  # Суперпользователь с полными правами


        # Обязательные настройки KRaft
        - name: KAFKA_ENABLE_KRAFT
          value: "yes"
        - name: KAFKA_CFG_PROCESS_ROLES
          value: "controller,broker"
        # id >= 1
        - name: KAFKA_CFG_CLUSTER_ID
          value: "1"
        - name: KAFKA_CFG_NODE_ID
          value: "1"
        - name: KAFKA_CFG_BROKER_ID
          value: "1"
        
        # Исправленные listener-настройки
        - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_CFG_LISTENERS
          value: "CLIENT://:9092,CONTROLLER://:9093"
        - name: KAFKA_CFG_ADVERTISED_LISTENERS
          value: "CLIENT://kafka-0.kafka:9092"  # Явное указание FQDN
        - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
          value: "CONTROLLER:PLAINTEXT,CLIENT:PLAINTEXT"
        - name: KAFKA_CFG_INTER_BROKER_LISTENER_NAME
          value: "CLIENT"
        - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
          value: "1@kafka-0.kafka:9093"
        
        # Системные переменные
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        
        volumeMounts:
        - name: kafka-data
          mountPath: /bitnami/kafka

  volumeClaimTemplates:
  - metadata:
      name: kafka-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 1Gi