apiVersion: v1
kind: Service
metadata:
  name: backend-user
spec:
  selector:
    app: user-pod
    tier: backend-user
  ports:
  - protocol: TCP
    port: 6002
    targetPort: 6002
  type: LoadBalancer