apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
spec:
  progressDeadlineSeconds: 240
  selector:
    matchLabels:
      app: user-pod
      tier: backend-user
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: user-pod
        tier: backend-user
        track: stable
    spec:
      volumes:
        - name: user-volume
          persistentVolumeClaim:
            claimName: user-persistent-volume-claim

      containers:
        - name: user-container
          image: grigorytitov/docker-call-center-user-image:v1
          imagePullPolicy: Always #Для подгрузки обновлений с DockerHub
          #command: ["npm","test"] #Для запуска тестов
          ports:
            - name: http
              containerPort: 6002
          env:
            #Testing working without email
            - name: TEST_EMAIL
              value: "test@gmail.com"
            - name: TEST_CODE
              value: "123456"
            #URL`S FOR SITE
            - name: URL_CORS
              value: "https://188-127-254-63.nip.io http://188-127-254-63.nip.io"
            - name: URL_SITE
              value: "https://188-127-254-63.nip.io/"
            - name: URL_BASE_INGRESS
              value: "https://188-127-254-63.nip.io/api/v1/user"
            - name: URL_OAUTH
              value: "https://188-127-254-63.nip.io/oauth"
            #External services
            - name: MAIL_SERVICE
              value: "yandex"
            - name: MAIL_USER
              value: "g.t1tov"
            - name: MAIL_FROM
              value: "g.t1tov@yandex.ru"
            - name: MAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailpassword
                  key: MAILPASSWORD

            - name: GITHUB_CLIENT_ID
              value: "Ov23liCbPZKQNRGiW25w"
            - name: GITHUB_URL_CALLBACK
              value: "/github/redirect"
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: githubpassword
                  key: GITHUBPASSWORD

            - name: GOOGLE_CLIENT_ID
              value: "304607294395-722pn96itl1ctappqio21qcjbe7tci7f.apps.googleusercontent.com"
            - name: GOOGLE_URL_CALLBACK
              value: "/google/redirect"
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: googlepassword
                  key: GOOGLEPASSWORD

            #Internal services
            - name: DB_USER
              value: postgres
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "db_users"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD

            - name: KAFKA_CLIENT_ID
              value: "user-app"
            - name: KAFKA_BROCKERS_HOST
              value: kafka
            - name: KAFKA_BROCKERS_PORT
              value: "9092"
            - name: KAFKA_BROCKERS_PARTIOTIONS
              value: "1"
            - name: KAFKA_BROCKERS_REPLICATION_FACTOR
              value: "1"

            - name: REDIS_NAME
              value: ""
            - name: REDIS_PASSWORD
              value: ""
            - name: REDIS_HOST
              value: redis
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_DB
              value: "1"
          volumeMounts:
            - mountPath: /public
              name: user-volume