apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: pg-storage
          persistentVolumeClaim:
            claimName: db-persistent-volume-claim
        - name: init-script
          configMap:
            name: postgres-init-db
            items:
              - key: init.sql
                path: init.sql  # Важно: создаст файл init.sql
      containers:
        - name: postgres-container
          image: postgres
          volumeMounts:
            - name: pg-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
            - name: init-script
              mountPath: /docker-entrypoint-initdb.d/  # Критически важно!
          env:
            - name: PGHOST
              value: postgres
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: PGDATABASE
              value: "postgres"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD